name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ vars.SSH_HOSTNAME }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

      - name: Deploy to DigitalOcean Droplet
        run: |
          cd ../opt/desprong
          docker-compose down
          docker pull ghcr.io/vandycktoon/opvolgingssysteem:backend-latest
          docker pull ghcr.io/vandycktoon/opvolgingssysteem:frontend-latest
          docker-compose up -d
