name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Hosting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ vars.SSH_HOSTNAME }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            cd ../opt/desprong
            docker-compose down
            docker rmi frontend-latest backend-latest
            docker pull ghcr.io/vandycktoon/opvolgingssysteem:backend-latest
            docker pull ghcr.io/vandycktoon/opvolgingssysteem:frontend-latest
            docker-compose up --build -d
            docker image prune -f
