name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to DigitalOcean Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@161.35.20.135 << 'EOF'
          cd ../opt/desprong
          docker-compose down
          docker pull ghcr.io/vandycktoon/opvolgingssysteem:backend-latest
          docker pull ghcr.io/vandycktoon/opvolgingssysteem:frontend-latest
          docker-compose up -d
          EOF
